jobs:
  build:
    name: Build
    needs:
      - checks
    permissions:
      actions: read
      checks: write
      contents: read
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
        with:
          submodules: 'true'
      - name: "~/.sbt\n\"~/.cache/coursier\"\n cache"
        uses: "actions/cache@v3"
        with:
          key: "${{ runner.os }}-sbt-${{ hashFiles('build.sbt', 'project/plugins.sbt', 'project/build.properties') }}"
          path: |
            ~/.sbt
            "~/.cache/coursier"
          restore-keys: |
            ${{ runner.os }}-sbt
      - name: "java ${{ matrix.java}} setup"
        uses: "actions/setup-java@v1.4.3"
        with:
          architecture: x64
          java-package: jdk
          java-version: "${{ matrix.java}}"
      - run: "sbt -DJDK_VERSION=${{ matrix.java}} \"++${{ matrix.scala}} test\""
      - if: "success() || failure()"
        name: Report test results
        uses: "dorny/test-reporter@v1.7.0"
        with:
          fail-on-error: 'true'
          name: SBT tests
          path: "target/test-reports/*.xml"
          reporter: java-junit
    strategy:
      matrix:
        java:
          - '17.0.9'
        scala:
          - '2.13.11'
  checks:
    name: Check formatting
    runs-on: ubuntu-latest
    steps:
      - uses: "actions/checkout@v2"
        with:
          submodules: 'true'
      - name: "~/.sbt\n\"~/.cache/coursier\"\n cache"
        uses: "actions/cache@v3"
        with:
          key: "${{ runner.os }}-sbt-${{ hashFiles('build.sbt', 'project/plugins.sbt', 'project/build.properties') }}"
          path: |
            ~/.sbt
            "~/.cache/coursier"
          restore-keys: |
            ${{ runner.os }}-sbt
      - name: java 17 setup
        uses: "actions/setup-java@v1.4.3"
        with:
          architecture: x64
          java-package: jdk
          java-version: '17'
      - run: sbt scalafmtCheckAll scalafmtSbtCheck
name: scall_build_and_test
on:
  push: {}
